"""Adicionar campos no modelo Atleta

Revision ID: a74a3be36214
Revises: <ID GERADO>
Create Date: 2025-04-06 23:46:30.403594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74a3be36214'
down_revision: Union[str, None] = '<ID GERADO>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('atletas', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=11),
               nullable=False)
    op.alter_column('atletas', 'idade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('atletas', 'peso',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('atletas', 'altura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('atletas', 'sexo',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.create_unique_constraint(None, 'atletas', ['cpf'])
    op.drop_column('atletas', 'pk_id')
    op.drop_column('atletas', 'data_nascimento')
    op.add_column('categorias', sa.Column('id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'categorias', ['nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorias', type_='unique')
    op.drop_column('categorias', 'id')
    op.add_column('atletas', sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('atletas', sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'atletas', type_='unique')
    op.alter_column('atletas', 'sexo',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('atletas', 'altura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('atletas', 'peso',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('atletas', 'idade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('atletas', 'cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=14),
               nullable=True)
    op.drop_column('atletas', 'id')
    # ### end Alembic commands ###
